name: Merge dev to main

on:
  workflow_dispatch: # 手动触发

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.APT }}
          fetch-depth: 0 # 获取所有分支和提交历史
          ref: dev
      # 设置 Git 用户信息
      - name: Set up Git user
        run: |
          git config user.name "FanGuangXin"
          git config user.email "18270985042@163.com"
      # 合并 dev 到 main
      - name: Merge dev into main
        id: merge_step
        run: |
          git checkout main
          git merge dev
          echo "merge_info=$(git log -1 --pretty=format:'哈希值: %h 
          提交者: %an 
          提交时间: %ar  
          提交注释: %s')" >> $GITHUB_ENV
          git push origin main

      # 合并成功/失败后通知
      - name: Send email on failure
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com # 你的SMTP服务器地址
          server_port: 465 # 你的SMTP服务器端口
          username: ${{ vars.EMAIL }} # 你的SMTP用户名
          password: ${{ vars.EMAIL_PASSWORD }} # 你的SMTP密码，存储在GitHub Secrets中
          subject: ${{ success() && '从dev合并到main成功' || '从dev合并到main失败' }}
          to: ${{ vars.EMAIL_TO  }} # 收件人邮箱
          from: ${{vars.EMAIL}} # 发件人邮箱
          body: |
            ${{
            success() && '从开发到主分支的自动合并成功。' || '从开发到主分支的自动合并失败, 请查看日志了解更多细节'
            }}
            最近一条合并信息如下
            ${{ env.merge_info }}
