name: Merge dev to main

on:
  schedule:
    - cron: "9 19 * * *" # 每天18点触发

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: dev # 检出dev分支

      - name: Merge dev into main
        run: |
          git config user.name "FanGuangXin"
          git config user.email "18270985042@163.com"
          git checkout main
          git merge dev --no-ff -m "Automated merge from dev to main"
          git push origin main

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com # 你的SMTP服务器地址
          server_port: 465 # 你的SMTP服务器端口
          username: ${{ vars.EMAIL }} # 你的SMTP用户名
          password: ${{ vars.EMAIL_PASSWORD }} # 你的SMTP密码，存储在GitHub Secrets中
          subject: "从dev合并到main失败"
          to: ${{ vars.EMAIL_TO  }} # 收件人邮箱
          from: vars.EMAIL # 发件人邮箱
          body: |
            从开发到主分支的自动合并失败。
            请查看日志了解更多细节。
